[package]
name = "reddit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = "2.9.1"
serde = {version="1.0.193",features=["derive"]}
serde_json = "1.0.108"
chrono = "0.4.31"
anyhow = "1.0.75"